/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.bundesbank.jdemetra.xlsx2ws.wizard.x13;

import de.bundesbank.jdemetra.xlsx2ws.spec.x13.SeriesSetting;
import javax.swing.JPanel;

public final class SeriesSettingVisual extends JPanel {

    public SeriesSettingVisual() {
        initComponents();
    }

    @Override
    public String getName() {
        return "Series Settings (X13)";
    }

    public SeriesSetting createSetting() {
        return new SeriesSetting(
                cbSpan.isSelected(),
                cbPreliminaryCheck.isSelected());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        cbSpan = new javax.swing.JCheckBox();
        cbPreliminaryCheck = new javax.swing.JCheckBox();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, "Choose which parts of the series specification (X13) should be written to the XLSX.");

        org.openide.awt.Mnemonics.setLocalizedText(cbSpan, "Span");

        org.openide.awt.Mnemonics.setLocalizedText(cbPreliminaryCheck, "Preliminary check");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(cbPreliminaryCheck)
                    .addComponent(cbSpan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbSpan)
                .addGap(18, 18, 18)
                .addComponent(cbPreliminaryCheck)
                .addContainerGap(204, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbPreliminaryCheck;
    private javax.swing.JCheckBox cbSpan;
    // End of variables declaration//GEN-END:variables

}
