/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.bundesbank.jdemetra.xlsx2ws.wizard.x13;

import de.bundesbank.jdemetra.xlsx2ws.spec.x13.TransformSetting;
import javax.swing.JPanel;

public final class TransformSettingVisual extends JPanel {

    public TransformSettingVisual() {
        initComponents();
    }

    @Override
    public String getName() {
        return "Transform Settings (X13)";
    }

    public TransformSetting createSetting() {
        return new TransformSetting(
                cbTransform.isSelected(),
                cbAicDiff.isSelected(),
                cbAdjust.isSelected());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        cbTransform = new javax.swing.JCheckBox();
        cbAicDiff = new javax.swing.JCheckBox();
        cbAdjust = new javax.swing.JCheckBox();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, "Choose which parts of the transform specification (X13) should be written to the XLSX.");

        org.openide.awt.Mnemonics.setLocalizedText(cbTransform, "Transform");

        org.openide.awt.Mnemonics.setLocalizedText(cbAicDiff, "AIC diff");

        org.openide.awt.Mnemonics.setLocalizedText(cbAdjust, "Adjust");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(cbAicDiff)
                    .addComponent(cbTransform)
                    .addComponent(cbAdjust))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbTransform)
                .addGap(18, 18, 18)
                .addComponent(cbAicDiff)
                .addGap(18, 18, 18)
                .addComponent(cbAdjust)
                .addContainerGap(163, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbAdjust;
    private javax.swing.JCheckBox cbAicDiff;
    private javax.swing.JCheckBox cbTransform;
    // End of variables declaration//GEN-END:variables

}
